### ISSUE TITLE
Simplify usage to make the default as run

### ISSUE THREAD

**Issue by calhauz** [dreadster3/buddy#7]
We know `buddy init|list|get` are "buddy" commands, but 99% of buddy's usage is `buddy run` isn't it possible to make the default be `buddy run`?

So that with the following `buddy.json`:
```json
{
  "name": "<project-name>",
  "version": "0.0.1",
  "description": "A new buddy project",
  "author": "Anonymous",
  "scripts": {
    "start": "go run main.go",
    "build": "go build -o dist/main main.go",
    "test": "go test"
  }
}
```

Instead of typing `buddy run start`, `buddy run build` and `buddy run test` we could just do `buddy start`, `buddy build` and `buddy test`? 
The only problem/edge case I see is that if we give a script the key of `init`, `list` or `get`, which are buddy cmds. For those cases we could invalidate the configuration or make sure buddy's cmds have priority so that in order to run our script "init" we must do `buddy run init` or something like that.

**Comment by dreadster3** [comment]
Issue tackled here #11
